namespace QuakeDemoFun
{
    public enum QMessageID : byte
    {
        Bad = 0,
        Nop,
        Disconnect,
        UpdateStat,
        Version,
        SetView,
        Sound,
        Time,
        Print,
        Stufftext,
        SetAngle,
        ServerInfo,
        LightStyle,
        UpdateName,
        UpdateFrags,
        ClientData,
        StopSound,
        UpdateColors,
        Particle,
        Damage,
        SpawnStatic,
        SpawnObsolete,
        SpawnBaseline,
        TempEntity,
        SetPause,
        SignOnNum,
        Centerprint,
        KilledMonster,
        FoundSecret,
        SpawnStaticSound,
        Intermission,
        Finale,
        CDTrack,
        SellScreen,
        CutScene,
        UpdateEntity = 0x80,
    }
}
